port: 3003
jwt_secret: "secret"
jwt_expire_time: 5
database:
    host: netadim-db
    port: 5432
    name: netadim
    user: netadim
    password: netadim
    sslmode: disable
    migrate: true

redis:
    host: "redis"
    port: "6379"
    password: ""
    db: 0 
    
prometheus:
    port: 9090

grafana:
    port: 3000    


# nats:
#   host: netadim-nats
#   port: 4222